"""Hard risk constraints and invariant definitions for the RECURZ Execution Engine.
"""

from enum import Enum


class RiskConstraint(str, Enum):
    """Identifiers for hard risk constraints and boundary checks."""
    NON_NEGATIVE_QUANTITY = "NON_NEGATIVE_QUANTITY"
    REMAINING_QUANTITY_CAP = "REMAINING_QUANTITY_CAP"
    MAX_PARTICIPATION_CAP = "MAX_PARTICIPATION_CAP"
    MAX_SINGLE_CHILD_CAP = "MAX_SINGLE_CHILD_CAP"
    SPREAD_THROTTLE = "SPREAD_THROTTLE"
    VOLATILITY_THROTTLE = "VOLATILITY_THROTTLE"
    ZERO_VOLUME_CLAMP = "ZERO_VOLUME_CLAMP"
    DEADLINE_EMERGENCY_OVERRIDE = "DEADLINE_EMERGENCY_OVERRIDE"
    ORDER_ALREADY_COMPLETED = "ORDER_ALREADY_COMPLETED"
